Initial basis
DBCDK/kbalc pull request #1
Opened 2023-06-23 07:35 UTC by srhb

Basic scaffolding +

This implements a (naive, but probably sufficient for our use case) balancer that moves replicas from the most-populated (by count, at least for now) logDir, to the least-populated logDir.

2023-06-26 06:45 UTC, estka commented
Can we add a readme? incl info on how to run and what command line args this tool expects

2023-06-26 10:47 UTC, estka commented
reply to comment on line 41-43:
after reading around it seems like it is fine 

https://stackoverflow.com/questions/35539956/defining-multiple-constant-variables-in-clojure
https://stackoverflow.com/questions/3267905/best-practice-for-globals-in-clojure-refs-vs-alter-var-root

If promises are not good enough there is the option of using an atom
https://clojuredocs.org/clojure.core/atom

2023-06-26 11:53 UTC, estka commented
I like the accurate import and the comment at  `core.clj:82``

2023-06-26 12:03 UTC, srhb commented
I'll take a look at your review tomorrow, thanks! (By the way, if you use "Review changes" from the "Files changed" tab, they become proper review comments that need resolution -- they don't have to be tied to lines. Just for next time :smile: )

2023-06-26 12:20 UTC, srhb commented
> Out of curiousity, is kbalc short for kafka balance?

I think it started out as "kafka balance clojure" but I'm happy to leave it up to the user to interpret it. :grin:

2023-06-26 12:31 UTC, srhb reviewed
Put some stuff in the README

2023-06-27 10:16 UTC, estka requested changes

2023-06-27 10:16 UTC, estka commented on src/kbalc/core.clj
> +;; again outside of main.
Looks fine to me.

Here is what the docs says about vars and the global environment
https://clojure.org/reference/vars

vars can e.g. be described :dynamic if they are likely to change, as :static is the default. If var is described :const and later redefined it will not affect code that consumes var as a as described as const is loaded into runtime env at compile time.

I am unsure if the is a synchronization primitive exactly like once in rust

A good idea with a comment when introducing global vars :D Alternatly to defing global vars you can set them up using an init function. In the end it is a matter of taste and tolerance to side-effects. An init function would also clean up main a bit
https://stackoverflow.com/questions/3267905/best-practice-for-globals-in-clojure-refs-vs-alter-var-root
https://stackoverflow.com/questions/48690768/in-clojure-how-to-change-def-a-variable-value-inside-a-function
the latter has some nice references

2023-06-27 10:16 UTC, estka commented on src/kbalc/core.clj
> +      (if (<= diff threshold)
What about adding some more error handling to prevent a NullPointerException when do-balance is called on a balanced cluster?
Alternatively use a different mechanism for terminating from do-balance when condition is not met - such as using when keyword , which has an implicit do

2023-06-27 10:16 UTC, estka commented on src/kbalc/core.clj
> +          ;; no comparing here yet, could use size or other smartness
Great comment

2023-06-27 10:16 UTC, estka commented on src/kbalc/core.clj
> +  (:import
Appreciate the accurate imports

2023-06-27 10:52 UTC, srhb commented on src/kbalc/core.clj
> +;; again outside of main.
No amount of `:static` `:const` or whatnot will change the issue I'm seeing here, which is that I want something where the following program is invalid,

```
(def foo) ;; "top level" or whatever we call it in clojure, to be in scope for print-foo (ie. I explicitly don't want to pass as argument to every function)

(defn print-foo [] (println foo))
(defn main [& args]
  (def foo 42) ;; value of 42 is really gotten from args, hence this can only be set in main
  (def foo 43) ;; this should fail
  (print-foo))
```

Anyway, as you implied it's not a big deal, so I don't think I intend to change anything unless someone has an example solution. :)

2023-06-27 10:59 UTC, estka commented on src/kbalc/core.clj
> +      (if (<= diff threshold)
```
Exception in thread "main" java.lang.NullPointerException
	at kbalc.core$_main.invokeStatic(core.clj:129)
	at kbalc.core$_main.doInvoke(core.clj:116)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at kbalc.core.main(Unknown Source)
```

2023-06-27 11:38 UTC, srhb commented on src/kbalc/core.clj
> +      (if (<= diff threshold)
Fixed in [cccdf40](https://github.com/DBCDK/kbalc/pull/1/commits/cccdf40a155a7f24f7bd0713737d178dfcb5506f)

2023-06-27 11:39 UTC, srhb commented
I believe I've addressed all your non-noop review comments, please click resolve if you agree. :)

2023-06-27 13:07 UTC, estka approved these changes

2023-06-27 13:08 UTC, merged